#!/bin/sh

#date '+%Y %b %d (%a) %T'
date '+%d %b %Y (%a) %T'

case $BLOCK_BUTTON in
	1) pgrep -x dunst >/dev/null && notify-send "$(cal --color=always | sed "s/..7m/<b><span color=\"red\">/;s/..27m/<\/span><\/b>/")" ;;
	3) "$TERMINAL" -e calcurse ;;
esac

